import tailwindcss from '@tailwindcss/vite'

export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },

  css: ['@fontsource-variable/inter', '~/assets/css/tailwind.css'],

  vite: {
    plugins: [tailwindcss()],
    optimizeDeps: {
      // UMD bundles: pre-bundle so the dev server doesn't reload on first import.
      include: ['qr-code-styling', 'jsqr'],
    },
  },

  modules: ['@vueuse/nuxt', '@nuxtjs/color-mode', 'shadcn-nuxt', '@vite-pwa/nuxt'],

  pwa: {
    registerType: 'autoUpdate',
    // Icons are committed under public/ and generated by `npm run icons`
    // (scripts/generate-icons.mjs). We deliberately avoid pwaAssets/sharp here: its
    // native binary fails to load on some Windows setups, and the plugin then omits
    // icons from the manifest silently.
    manifest: {
      name: 'SweetQR — QR code toolkit',
      short_name: 'SweetQR',
      description:
        'Create, customise, export and scan QR codes. Fast, private and entirely local to your browser.',
      theme_color: '#4f46e5',
      background_color: '#ffffff',
      display: 'standalone',
      start_url: '/',
      scope: '/',
      categories: ['utilities', 'productivity'],
      icons: [
        { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
        { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
        { src: '/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
    },
    workbox: {
      globPatterns: ['**/*.{js,css,html,svg,png,ico,webp,woff,woff2}'],
      // The app shell handles every route; navigateFallback keeps offline reloads working.
      navigateFallback: '/',
      cleanupOutdatedCaches: true,
    },
    client: {
      installPrompt: true,
    },
    devOptions: {
      // Lets the service worker be exercised during `npm run dev` when needed.
      enabled: false,
    },
  },

  components: [
    // pathPrefix: false gives us <QrPreview> rather than <QrQrPreview>.
    // components/ui is owned by shadcn-nuxt, so it stays out of this scan.
    { path: '~/components', pathPrefix: false, ignore: ['**/ui/**'] },
  ],

  shadcn: {
    prefix: '',
    componentDir: '~/components/ui',
  },

  colorMode: {
    classSuffix: '',
    preference: 'system',
    fallback: 'light',
  },

  app: {
    head: {
      title: 'SweetQR',
      htmlAttrs: { lang: 'en' },
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        {
          name: 'description',
          content:
            'Create, customize, export and scan QR codes. Fast, private and entirely local to your browser.',
        },
        { name: 'theme-color', content: '#ffffff', media: '(prefers-color-scheme: light)' },
        { name: 'theme-color', content: '#0b0b12', media: '(prefers-color-scheme: dark)' },
      ],
      link: [
        { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' },
        { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' },
      ],
    },
  },
})
